services:
  product-catalogue-dev:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_PATH=/app/data/products.db
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - ./data:/app/data
      - /app/node_modules
      - /app/backend/node_modules
      - /app/frontend/node_modules
    command: ["npm", "run", "dev"]
    restart: unless-stopped